language: c
compiler:
  - gcc

before_install:
  - echo "deb http://download.opensuse.org/repositories/home:/VPetya:/zorp/xUbuntu_12.04/ ./" | sudo tee -a /etc/apt/sources.list
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_12.04/ /' >> /etc/apt/sources.list.d/osc.list"
  - wget -qO - http://download.opensuse.org/repositories/home:/VPetya:/zorp/xUbuntu_12.04/Release.key | sudo apt-key add -
  - wget -qO - http://download.opensuse.org/repositories/openSUSE:Tools/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/a/automake/automake1.4_1.4-p6-13.1_all.deb
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/a/autoconf/autoconf_2.69-6_all.deb
  - sudo dpkg -i autoconf_2.69-6_all.deb
  - sudo dpkg -i automake1.4_1.4-p6-13.1_all.deb
  - sudo apt-get update -qq
  - echo -e "" | sudo apt-get install osc

script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i
  - autoreconf -i
  - ./configure
  - make

after_success:
  - dpkg-buildpackage -S
  - echo -e "addFilter(\".*\") \n" > ../zorp-iptables-addons.rpmlintrc
  - cp rpm/* ../
  - echo -e "[general]\napiurl = https://api.opensuse.org\n[https://api.opensuse.org]\nuser = VPetya\npass = $PASS\n" > ~/.oscrc
  - osc co home:VPetya:travis
  - rm home:VPetya:travis/zorp-iptables-addons/*
  - mv ../*.* home:VPetya:travis/zorp-iptables-addons
  - cd home:VPetya:travis/zorp-iptables-addons
  - osc addremove
  - osc commit -m "TRAVIS"

env:
  global:
    secure: clHXFWvTEqxxU3Ct8u3f3anzaLE+Jns4alMEs0ZxmOMCNFnff/zQ4ouht380afcWrRmo09+kLJc8PjmYxS1DLh2qIFO/lZf1ORf4HEC0utbrt8diH4fJc+LuWk8kkrFJZfbV21gdQUvJxO8MyQnuwLzlZkE98km49oFNujhSGGk=
