language: c
compiler:
 - gcc
 - clang
branches:
  only:
    - travis
before_install:
  - wget  -qO - http://download.opensuse.org/repositories/security:/Zorp/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i
  - autoreconf -i
  - ./configure
  - make
after_success:
  - dpkg-buildpackage -S
