language: c
compiler:
  - gcc
branches:
  only:
  - travis
before_install:
  - wget  -qO - http://download.opensuse.org/repositories/security:/Zorp/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i
  - autoreconf -i
  - ./configure
  - make
before_deploy:
  - dpkg-buildpackage -S
deploy:
  provider: releases
  api_key:
    secure: rOgy7DdkMCHxJgKzzDk+s6otFJ4jjglMgHRyTgOF/XCq0DBkvJ8ef2dAFIAG1+wvB44P97BYzSnvGEohDviLYNpLXPWMx1XGG9SU8qLcjgFh3KLcWP1sMVTdcng/bU1b8qHJHRXJ/SVhVrEvWGD3ZXfr6cyv2hjPWTP1GClK8Ys=
  file:
    - "../iptables-addons_1.0-1.dsc"
    - "../iptables-addons_1.0-1.tar.gz"
  on:
    repo: balabit/zorp-iptables-addons
    branch: travis
